# -*- coding: utf-8 -*-
"""curso Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yev13imnLyw7i37CBoeITQWxsObVOXV4

Criando meu primeiro programa
"""

print('Olá,mundo!')

"""Nomeando variáveis e testando print"""

nome = "Juan"
idade = 25
altura = 1.75
estudante = True
print(nome,idade,estudante)

"""Utilizando o mesmo valor para várias variáveis"""

a=b=c=10
print(c)
print(b)
print(a)

"""Testando operadores aritméticos"""

a = 10
b = 3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

"""Testando operadores de comparação"""

a = 10
b = 3
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

"""Operadores Lógicos"""

a = 10
b = 3
print(a < b) and (b > a)
print(a > b) or (a < b)
print(not a < b)
print(not b > a)

a = 5
b = 25
resultado1 = (a < b) or (b > a)
print(resultado1)

"""Estruturas condicionais
IF(se)
"""

idade = 37
if idade >= 18:
  print('Você é maior de idade.')

"""If else"""

idade = 14
if idade >= 18:
  print( 'Você é maior de idade!')
else:
    print('Você é menor de  idade!')

"""If Elif Else"""

nota  = 100
if nota >= 90:
  print('Excelente')
elif nota >= 80:
  print('Muito bom')
elif nota >= 70:
  print('Bom')
else:
  print('RECUPERAÇÃO')

"""f"" (f-string)
É uma forma especial de escrever textos com variáveis dentro.

A letra f antes das aspas indica:

“Esse texto contém valores que devem ser substituídos por variáveis.”

As f-strings (f"texto {variavel}") permitem juntar texto e variáveis facilmente.
"""

nome = "Agatha"
idade = 25
altura = 1.55

print(f"Nome: {nome}")
print(f"Idade: {idade}")
print(f"Altura: {altura}")

"""Recebendo numeros do usuário:

input() → Pede para o usuário digitar algo

float() → Converte o texto digitado para número decimal (com vírgula/ponto)

num1 → Guarda esse número na variável num1
(same para num2)
"""

# Entrada de Dados
num1 = float(input("Digite o primeiro número:"))
num2 = float(input("Digite o segundo número:"))
num3 = float(input("Digite o terceiro número:"))

#Calculo
soma = num1 + num2 + num3
media = (num1 + num2 + num3) / 2

"""As estruturas de controle são ferramentas poderosas que nos permitem controlar o fluxo de execução de nossos programas. Com as estruturas condicionais (if, if-else, if-elif-else) podemos tomar decisões baseadas em condições, enquanto que com os loops (for, while) podemos repetir blocos de código várias vezes. Além disso, as instruções break, continue e pass nos fornecem um controle adicional sobre o comportamento dos loops.

"""

frutas = ["uva", "pêra", "morango"]


for fruta in frutas:
    print(fruta)

"""Loops: FOR

While
"""

contador = 0

while contador < 5:
    print(contador)
    contador += 1

contador = 0


while True:

    print(contador)
    contador += 1


    if contador == 10:
        break



for i in range(10):

    if i % 4 == 0:
        continue
    print(i)

"""Métodos de listas
As listas em Python têm vários métodos incorporados que nos permitem manipular e modificar os elementos da lista. Alguns métodos comuns são:

append(elemento): adiciona um elemento ao final da lista.
insert(indice, elemento): insere um elemento em uma posição específica da lista.
remove(elemento): remove a primeira ocorrência de um elemento na lista.
pop(indice): remove e retorna o elemento em uma posição específica da lista.
sort(): ordena os elementos da lista em ordem ascendente.
reverse(): inverte a ordem dos elementos na lista.
"""

frutas = ["maçã", "banana", "laranja"]


frutas.append("pera")
print(frutas)  # Imprime ["maçã", "banana", "laranja", "pera"]


frutas.insert(2, "uva")
print(frutas)  # Imprime ["maçã", "banana", "uva", "laranja", "pera"]


frutas.remove("banana")
print(frutas)  # Imprime ["maçã", "uva", "laranja", "pera"]


fruta_removida = frutas.pop(2)
print(frutas)  # Imprime ["maçã", "uva", "pera"]
print(fruta_removida)  # Imprime "laranja"


frutas.sort()
print(frutas)  # Imprime ["maçã", "pera", "uva"]


frutas.reverse()
print(frutas)  # Imprime ["uva", "pera", "maçã"]

"""Lista de compreensão

if x % 1 == 0 (todo mundo que for multiplo de  "1" nesse exemplo)

[x ** 2 (elevar ao quadrado)
"""

números = [1, 2, 3, 4, 5]
quadrados = [x ** 2 for x in números if x % 2 == 0]
print(quadrados)  # Imprime [4, 16]

"""Dicionários"""

pessoa = {"nome": "João", "idade": 25, "cidade": "Madri"}
print(pessoa["nome"])  # Imprime "João"
print(pessoa["idade"])    # Imprime 25
print(pessoa["cidade"])  # Imprime "Madri"

"""Métodos de dicionários
Os dicionários em Python têm vários métodos incorporados para manipular e acessar os elementos. Alguns métodos comuns são:

keys(): retorna uma visualização de todas as chaves do dicionário.
values(): retorna uma visualização de todos os valores do dicionário.
items(): retorna uma visualização de todos os pares chave-valor do dicionário.
update(outro_dicionario): atualiza o dicionário com os pares chave-valor de outro dicionário.
"""

pessoa = {"nome": "João", "idade": 25, "cidade": "Madri"}


print(pessoa.keys())    # Imprime dict_keys(["nome", "idade", "cidade"])
print(pessoa.values())  # Imprime dict_values(["João", 25, "Madri"])
print(pessoa.items())   # Imprime dict_items([("nome", "João"), ("idade", 25), ("cidade", "Madri")])


pessoa.update({"profissao": "Engenheiro"})
print(pessoa)  # Imprime {"nome": "João", "idade": 25, "cidade": "Madri", "profissao": "Engenheiro"}

"""As estruturas de dados em Python nos oferecem grande flexibilidade e potência para armazenar e manipular dados em nossos programas. As listas são úteis para coleções ordenadas e mutáveis, as tuplas para coleções ordenadas e imutáveis, os dicionários para armazenar pares de chave valor e os conjuntos para coleções não ordenadas de elementos únicos."""

conjunto1 = {1, 2, 3}
conjunto2 = {3, 4, 5}


uniao = conjunto1 | conjunto2
print(uniao)  # Imprime {1, 2, 3, 4, 5}


intersecao = conjunto1 & conjunto2
print(intersecao)  # Imprime {3}


diferenca = conjunto1 - conjunto2
print(diferenca)  # Imprime {1, 2}


diferenca_simetrica = conjunto1 ^ conjunto2
print(diferenca_simetrica)  # Imprime {1, 2, 4, 5}

frutas = {"maçã", "banana", "laranja"}


frutas.add("pera")
print(frutas)  # Imprime {"maçã", "banana", "laranja", "pera"}


frutas.remove("banana")
print(frutas)  # Imprime {"maçã", "laranja", "pera"}


frutas.discard("uva")
print(frutas)  # Imprime {"maçã", "laranja", "pera"}


frutas.clear()
print(frutas)  # Imprime set()

def saudacao():
    print("Olá, mundo!")
def nome():
  print("Estudante de Ciências de Dados")

saudacao()  # Imprime "Olá, mundo!"
nome()

def saudacao(nome):
    print(f"Olá, {nome}!")

saudacao("Ágatha")
saudacao("Tiago")
saudacao("Jennifer")

from ast import Mult
def multiplicar(a, b):
    return a * b


resultado = multiplicar(3, 4)
print(resultado)

elevadoa5 = lambda x: x ** 5
print(elevadoa5(2))

def funcao():
    variavel_local = 10
    print(variavel_local)  # Acessível dentro da função


variavel_global = 20


def funcao2():
    print(variavel_global)  # Acessível de qualquer lugar


funcao()  # Imprime 10
funcao2()  # Imprime 20
print(variavel_global)  # Imprime 20
print(variavel_local)  # Gera um erro, a variável não está definida neste escopo.

"""As funções são uma ferramenta fundamental na programação e nos permitem estruturar e modularizar nosso código. Com a capacidade de definir funções personalizadas, podemos encapsular tarefas específicas e reutilizá-las em diferentes partes do nosso programa.

Além das funções definidas pelo usuário, Python também fornece uma ampla gama de funções incorporadas que podemos utilizar diretamente, como print(), len(), range(), entre outras.

Documentação de funções (docstrings)
É uma boa prática documentar nossas funções utilizando docstrings. Os docstrings são cadeias de texto que descrevem o propósito, os parâmetros e o valor de retorno de uma função. São colocados imediatamente após a definição da função e são encerrados entre aspas duplas triplas.
"""

def area_retangulo(base, altura):
    """
    Calcula a área de um retângulo.


    Args:
        base (float): A base do retângulo.
        altura (float): A altura do retângulo.


    Returns:
        float: A área do retângulo.
    """
    return base * altura

nome = input("Insira seu nome: ")
idade = input("Insira sua idade: ")


print("Olá, " + nome + "!")
print("Você tem " + idade + " anos.")

idade = int(input("Insira sua idade: "))


if idade >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")

nome = "Juan"
idade = 25


print(f"Olá, meu nome é {nome} e tenho {idade} anos.")

from math import sqrt


resultado = sqrt(16)
print(resultado)  # Imprime 5.0

import random
import datetime


numeroaleatorio = random.randint(1, 10)
print(numeroaleatorio)  # Imprime um número inteiro aleatório entre 1 e 10


data_atual = datetime.datetime.now()
print(data_atual)  # Imprime a data e hora atual